# Generated by Django 4.1.6 on 2023-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcamp',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
